"""Shared defaults for persisted application settings."""

DEFAULT_SERVER_NAME = "Ragtime"
DEFAULT_AUTHENTICATED_WEBGL_BACKGROUND_ENABLED = True
DEFAULT_OPENAPI_MODEL_PREFIX_ENABLED = True

DEFAULT_EMBEDDING_PROVIDER = "ollama"
DEFAULT_EMBEDDING_MODEL = "nomic-embed-text"

DEFAULT_LLM_PROVIDER = "openai"
DEFAULT_LLM_MODEL = "gpt-4-turbo"

DEFAULT_MAX_QUERY_RESULTS = 100
DEFAULT_QUERY_TIMEOUT_SECONDS = 30
DEFAULT_HTTP_PROXY_SAFE_TIMEOUT_SECONDS = 90

DEFAULT_MAX_TOOL_OUTPUT_CHARS = 5000
DEFAULT_SCRATCHPAD_WINDOW_SIZE = 6

DEFAULT_SEARCH_RESULTS_K = 5
DEFAULT_AGGREGATE_SEARCH = True
DEFAULT_SEARCH_USE_MMR = True
DEFAULT_SEARCH_MMR_LAMBDA = 0.5
DEFAULT_CONTEXT_TOKEN_BUDGET = 4000
DEFAULT_IVFFLAT_LISTS = 100

DEFAULT_CHUNKING_USE_TOKENS = True
DEFAULT_CHUNKING_MAX_WORKERS = 4
DEFAULT_CHUNKING_MAX_BATCH_SIZE = 100
DEFAULT_SEQUENTIAL_INDEX_LOADING = False

DEFAULT_LLM_MAX_TOKENS = 4096
DEFAULT_IMAGE_PAYLOAD_MAX_WIDTH = 1024
DEFAULT_IMAGE_PAYLOAD_MAX_HEIGHT = 1024
DEFAULT_IMAGE_PAYLOAD_MAX_PIXELS = 786_432
DEFAULT_IMAGE_PAYLOAD_MAX_BYTES = 350_000
DEFAULT_IMAGE_PAYLOAD_LIMITS = {
    "max_width": DEFAULT_IMAGE_PAYLOAD_MAX_WIDTH,
    "max_height": DEFAULT_IMAGE_PAYLOAD_MAX_HEIGHT,
    "max_pixels": DEFAULT_IMAGE_PAYLOAD_MAX_PIXELS,
    "max_bytes": DEFAULT_IMAGE_PAYLOAD_MAX_BYTES,
}

DEFAULT_MAX_ITERATIONS = 15
DEFAULT_CHAT_COMPACTION_THRESHOLD_PERCENT = 80
DEFAULT_CHAT_AUTO_COMPACTION_THRESHOLD_PERCENT = 99
DEFAULT_OPENAPI_SYNC_CHAT_MODELS = True

DEFAULT_OCR_CONCURRENCY_LIMIT = 1
DEFAULT_OCR_MODE = "disabled"
DEFAULT_OCR_PROVIDER = "ollama"
DEFAULT_OLLAMA_EMBEDDING_TIMEOUT_SECONDS = 180

DEFAULT_TOOL_OUTPUT_MODE = "default"

DEFAULT_INCLUDE_COPILOT_THIRD_PARTY_MODELS = False
DEFAULT_GITHUB_COPILOT_BASE_URL = "https://api.githubcopilot.com"

DEFAULT_MCP_ENABLED = False
DEFAULT_MCP_DEFAULT_ROUTE_AUTH = False
DEFAULT_MCP_DEFAULT_ROUTE_AUTH_METHOD = "password"

DEFAULT_SNAPSHOT_RETENTION_DAYS = 0
DEFAULT_SNAPSHOT_STALE_BRANCH_THRESHOLD = 50

DEFAULT_USERSPACE_DUPLICATE_COPY_FILES = True
DEFAULT_USERSPACE_DUPLICATE_COPY_METADATA = True
DEFAULT_USERSPACE_DUPLICATE_COPY_CHATS = False
DEFAULT_USERSPACE_DUPLICATE_COPY_MOUNTS = False

# Legacy tool-target container defaults (deprecated — prefer ToolConfig)
DEFAULT_LEGACY_ODOO_CONTAINER = "odoo-server"
DEFAULT_LEGACY_POSTGRES_CONTAINER = "odoo-postgres"
DEFAULT_LEGACY_POSTGRES_PORT = 5432

DEFAULT_USERSPACE_MOUNT_SYNC_INTERVAL_SECONDS = 30
