use_default_settings: true

general:
  instance_name: "Ragtime Search"
  debug: false

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  base_url: http://searxng:8080/
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "ragtime-internal-searxng"
  limiter: false
  public_instance: false
  image_proxy: false
  method: "GET"

outgoing:
  request_timeout: 5.0
  max_request_timeout: 10.0
  pool_connections: 100
  pool_maxsize: 20
