from typing import Any

class _Model:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class IndexJob(_Model): ...
class IndexMetadata(_Model): ...
class User(_Model): ...

def __getattr__(name: str) -> Any: ...
